"""
dataset/upper_loader.py
───────────────────────────────────────────────────────────────────────────
PyTorch Dataset and DataLoader for the upper-limb CTR-GCN pipeline.

Expected directory layout
─────────────────────────
processed_dataset_upper/
    skeletons/
        <sample_name>.npy       shape (4, 300, 8, 1) float32
    train_labels.csv            columns: sample_name, label
    test_labels.csv             columns: sample_name, label
    upper_class_map.csv         columns: class_name, label

Label CSV format
────────────────
    sample_name,label
    Shoulder-Lateral-Rotation,0
    Elbow Soft Tissue Release,1
    ...

Labels are already integer class indices; no mapping needed here.

Augmentation (training only)
─────────────────────────────
• Random Gaussian noise  N(0, σ=0.01) on x/y/z channels
• Random temporal flip   (reverse T axis) with p=0.5
• Random left↔right mirror  (swap symmetric joint pairs) with p=0.5
"""

import csv
import os
from pathlib import Path
from typing import Optional

import numpy as np
import torch
from torch.utils.data import DataLoader, Dataset

# ── Expected tensor shape ─────────────────────────────────────────────────────

EXPECTED_C = 4
EXPECTED_T = 300
EXPECTED_V = 8   # 8 upper-limb nodes
EXPECTED_M = 1

# Dynamic num_workers default — 0 on CPU/MPS, up to 8 on CUDA
_DEFAULT_WORKERS = min(8, os.cpu_count() or 1) if __import__('torch').cuda.is_available() else 0

# ── Symmetric joint pairs for left↔right mirroring ───────────────────────────
# (left_node, right_node) — swapping these flips the bilateral skeleton

UPPER_MIRROR_PAIRS = [
    (0, 1),   # Left Shoulder  ↔ Right Shoulder
    (2, 3),   # Left Elbow     ↔ Right Elbow
    (4, 5),   # Left Wrist     ↔ Right Wrist
    (6, 7),   # Left Hip       ↔ Right Hip
]


# ─────────────────────────────────────────────────────────────────────────────
#  Helper: load dynamic class map
# ─────────────────────────────────────────────────────────────────────────────

def load_class_map(class_map_csv: str) -> dict[int, str]:
    """
    Load the integer-label → class-name mapping from the CSV generated by
    split_upper_dataset.py.

    Returns {label_int: class_name}.
    Falls back to a default map if the file doesn't exist.
    """
    path = Path(class_map_csv)
    if not path.exists():
        # Fallback — will be overwritten once split is run
        return {
            0: "elbow",
            1: "shoulder",
            2: "shoulder_flexion",
            3: "shoulder_rotation",
        }

    class_map: dict[int, str] = {}
    with open(path, newline="", encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            class_map[int(row["label"])] = row["class_name"]
    return class_map


# ─────────────────────────────────────────────────────────────────────────────
#  Dataset
# ─────────────────────────────────────────────────────────────────────────────

class UpperPhysioDataset(Dataset):
    """
    Loads upper-limb skeleton tensors and integer class labels for CTR-GCN.

    Args:
        labels_csv    (str):  path to CSV with columns [sample_name, label].
        skeleton_dir  (str):  directory containing ``<sample_name>.npy`` files.
        augment       (bool): apply on-the-fly data augmentation (training only).
        noise_sigma   (float): std of Gaussian noise added to x/y/z channels.
    """

    def __init__(
        self,
        labels_csv:   str,
        skeleton_dir: str,
        augment:      bool  = False,
        noise_sigma:  float = 0.01,
    ):
        self.skeleton_dir = skeleton_dir
        self.augment      = augment
        self.noise_sigma  = noise_sigma

        self.samples: list[dict] = []
        self._load_csv(labels_csv)

    # ── CSV loading ───────────────────────────────────────────────────────────

    def _load_csv(self, path: str) -> None:
        with open(path, newline="", encoding="utf-8") as fh:
            reader = csv.DictReader(fh)
            for row in reader:
                name = (row.get("sample_name") or "").lstrip()
                raw  = (row.get("label") or "").strip()
                if not name or not raw:
                    continue
                self.samples.append({
                    "sample_name": name,
                    "label":       int(raw),
                })
        if not self.samples:
            raise ValueError(f"No valid rows found in {path}")

    # ── Standard Dataset interface ────────────────────────────────────────────

    def __len__(self) -> int:
        return len(self.samples)

    def __getitem__(self, idx: int):
        row   = self.samples[idx]
        name  = row["sample_name"]
        label = row["label"]

        data = self._load_tensor(name)      # (C, T, V, M) float32

        if self.augment:
            data = self._augment(data)

        target = torch.tensor(label, dtype=torch.long)
        return data, target, name

    # ── Tensor loading with shape validation ──────────────────────────────────

    def _load_tensor(self, sample_name: str) -> torch.Tensor:
        path = os.path.join(self.skeleton_dir, f"{sample_name}.npy")
        if not os.path.exists(path):
            raise FileNotFoundError(f"Skeleton file not found: {path}")

        arr = np.load(path).astype(np.float32)

        if arr.shape != (EXPECTED_C, EXPECTED_T, EXPECTED_V, EXPECTED_M):
            raise ValueError(
                f"[{sample_name}] Bad tensor shape {arr.shape}. "
                f"Expected ({EXPECTED_C}, {EXPECTED_T}, {EXPECTED_V}, {EXPECTED_M})."
            )

        return torch.from_numpy(arr)

    # ── Augmentation ──────────────────────────────────────────────────────────

    def _augment(self, x: torch.Tensor) -> torch.Tensor:
        """
        x : (C, T, V, M)  float32

        Augmentations:
          1. Gaussian noise on channels 0,1,2 (x, y, z); skip channel 3 (visibility)
          2. Temporal flip with p=0.5
          3. Left-right joint mirror with p=0.5
        """
        x = x.clone()

        # 1. Gaussian noise on x, y, z
        if self.noise_sigma > 0:
            noise = torch.randn_like(x[:3]) * self.noise_sigma
            x[:3] = x[:3] + noise

        # 2. Temporal flip
        if torch.rand(1).item() < 0.5:
            x = x.flip(dims=[1])

        # 3. Left-right mirror
        if torch.rand(1).item() < 0.5:
            x = x.clone()
            for l, r in UPPER_MIRROR_PAIRS:
                tmp = x[:, :, l, :].clone()
                x[:, :, l, :] = x[:, :, r, :]
                x[:, :, r, :] = tmp

        return x

    # ── Convenience properties ────────────────────────────────────────────────

    @property
    def class_distribution(self) -> dict[int, int]:
        from collections import Counter
        return dict(Counter(s["label"] for s in self.samples))

    @property
    def present_classes(self) -> list[int]:
        return sorted(self.class_distribution.keys())


# ─────────────────────────────────────────────────────────────────────────────
#  Factory helper
# ─────────────────────────────────────────────────────────────────────────────

def build_upper_loaders(
    train_csv:    str,
    test_csv:     str,
    skeleton_dir: str,
    batch_size:   int = 8,
    num_workers:  int = _DEFAULT_WORKERS,
) -> tuple[UpperPhysioDataset, UpperPhysioDataset, DataLoader, DataLoader]:
    """
    Build train + test Datasets and DataLoaders for the upper-limb pipeline.

    Returns:
        train_dataset, test_dataset, train_loader, test_loader
    """
    train_ds = UpperPhysioDataset(train_csv, skeleton_dir, augment=True)
    test_ds  = UpperPhysioDataset(test_csv,  skeleton_dir, augment=False)

    pin = torch.cuda.is_available()

    train_loader = DataLoader(
        train_ds,
        batch_size  = batch_size,
        shuffle     = True,
        num_workers = num_workers,
        pin_memory  = pin,
        persistent_workers = (num_workers > 0),
        drop_last   = False,
    )
    test_loader = DataLoader(
        test_ds,
        batch_size  = batch_size,
        shuffle     = False,
        num_workers = num_workers,
        pin_memory  = pin,
        persistent_workers = (num_workers > 0),
        drop_last   = False,
    )
    return train_ds, test_ds, train_loader, test_loader


# ── Standalone smoke-test ─────────────────────────────────────────────────────

if __name__ == "__main__":
    import sys

    base         = Path(__file__).parent.parent / "datasets/upper_limb"
    train_csv    = str(base / "train_labels.csv")
    test_csv     = str(base / "test_labels.csv")
    skeleton_dir = str(base / "skeletons")

    train_ds, test_ds, train_loader, test_loader = build_upper_loaders(
        train_csv, test_csv, skeleton_dir, batch_size=4
    )

    print(f"Train samples      : {len(train_ds)}")
    print(f"Test  samples      : {len(test_ds)}")
    print(f"Train class dist   : {train_ds.class_distribution}")
    print(f"Test  class dist   : {test_ds.class_distribution}")

    batch, labels, names = next(iter(train_loader))
    print(f"Batch tensor shape : {tuple(batch.shape)}")
    print(f"Batch labels       : {labels.tolist()}")
    print(f"Batch sample names : {list(names)}")
